default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mvcHome_development

test:
  <<: *default
  database: mvcHome_test

production:
  <<: *default
  database: mvcHome_production
  username: postgres
  password: <%= ENV['YOUR_APP_NAME_HERE_DATABASE_PASSWORD'] %>